---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-manager"
    clabernetes/component: manager-http
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 10443
  selector:
    clabernetes/app: {{ .Values.appName }}
    clabernetes/name: "{{ .Values.appName }}-manager"
    clabernetes/component: manager